version: '3'

services:
  ruby-service-dev:
    build:
      context: ./
      dockerfile: Dockerfile

    ports:
      - 4000:3000
    volumes:
      - ./:/usr/src/app
    command: rails s -b '0.0.0.0'
    depends_on:
      - postgres-service-dev

  postgres-service-dev:
    image: postgres:10.1
    environment:
      - POSTGRES_PASSWORD:${POSTGRES_PASSWORD}
    volumes:
      - ./data-persistence/postgres:/var/lib/postgresql/data
    ports:
      - "5433:5432"
